import {
  EmergencyAlert,
  Shelter,
  SafeRoute,
  EmergencyContact,
  EarthquakeEvent,
  GroundMotionSignal,
  NotificationChannelStatus,
  SourceMetadata,
  AuditLogItem,
} from '../types';

export const SEED_SOURCES: SourceMetadata[] = [
  {
    id: 'src-ksdma-gov',
    name: 'State Disaster Management Authority (SDMA)',
    tier: 1,
    tierName: 'Tier 1: Official National/State Government Authority',
    type: 'government',
    verified: true,
    endpointStatus: 'operational',
    lastSuccessfulUpdate: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    reliabilityScore: 98,
  },
  {
    id: 'src-imd-met',
    name: 'India Meteorological Department (IMD)',
    tier: 2,
    tierName: 'Tier 2: Verified Scientific / Meteorological Agency',
    type: 'weather',
    verified: true,
    endpointStatus: 'operational',
    lastSuccessfulUpdate: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    reliabilityScore: 95,
  },
  {
    id: 'src-cwc-flood',
    name: 'Central Water Commission (CWC River Gauge Network)',
    tier: 4,
    tierName: 'Tier 4: Automated River & Environmental Sensor Signal',
    type: 'sensor',
    verified: true,
    endpointStatus: 'operational',
    lastSuccessfulUpdate: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    reliabilityScore: 92,
  },
  {
    id: 'src-redcross-ops',
    name: 'Red Cross Emergency Operations Center',
    tier: 3,
    tierName: 'Tier 3: Verified Humanitarian Operational Partner',
    type: 'first_responder',
    verified: true,
    endpointStatus: 'operational',
    lastSuccessfulUpdate: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    reliabilityScore: 88,
  },
  {
    id: 'src-seismic-ncs',
    name: 'National Center for Seismology (NCS / USGS Feed)',
    tier: 2,
    tierName: 'Tier 2: Verified Seismic Network Agency',
    type: 'seismic',
    verified: true,
    endpointStatus: 'demo_data',
    lastSuccessfulUpdate: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    reliabilityScore: 94,
  },
  {
    id: 'src-citizen-reports',
    name: 'Citizen Field Spotter Reports (Social / App)',
    tier: 5,
    tierName: 'Tier 5: Unverified Crowd / Citizen Signal',
    type: 'public_report',
    verified: false,
    endpointStatus: 'operational',
    lastSuccessfulUpdate: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    reliabilityScore: 45,
  },
];

export const SEED_SHELTERS: Shelter[] = [
  {
    id: 'shelter-kollam-01',
    name: 'St. Aloysius Higher Secondary Relief Center',
    district: 'Kollam',
    location: {
      lat: 8.8932,
      lng: 76.6141,
      address: 'Beach Road, Cantonment Ward, Kollam',
      landmark: 'Near District Sports Complex',
    },
    capacity: 650,
    occupancy: 410,
    status: 'open',
    wheelchairAccessible: true,
    medicalSupport: true,
    emergencyPower: true,
    contactNumber: '+91 474 279 4001',
    source: 'District Administration Official Shelter Registry',
    lastUpdated: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
  },
  {
    id: 'shelter-alappuzha-02',
    name: 'SDV Centennial Community Hall & High Ground Shelter',
    district: 'Alappuzha',
    location: {
      lat: 9.4981,
      lng: 76.3388,
      address: 'Palace Road, Cullen Compound, Alappuzha',
      landmark: 'Elevated concrete superstructure, 1.2km from Main Canal',
    },
    capacity: 450,
    occupancy: 390,
    status: 'nearing_capacity',
    wheelchairAccessible: true,
    medicalSupport: true,
    emergencyPower: true,
    contactNumber: '+91 477 225 1700',
    source: 'Alappuzha Disaster Management Cell',
    lastUpdated: new Date(Date.now() - 9 * 60 * 1000).toISOString(),
  },
  {
    id: 'shelter-idukki-03',
    name: 'Nedumkandam Government College Evacuation Camp',
    district: 'Idukki',
    location: {
      lat: 9.8354,
      lng: 77.1425,
      address: 'Munnar-Kumily Highway, Nedumkandam',
      landmark: 'Stable bedrock elevation above landslide danger contour',
    },
    capacity: 800,
    occupancy: 215,
    status: 'open',
    wheelchairAccessible: false, // Transparent, never invent!
    medicalSupport: true,
    emergencyPower: true,
    contactNumber: '+91 486 823 2050',
    source: 'Revenue Divisional Officer, Idukki',
    lastUpdated: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
  },
];

export const SEED_ROUTES: SafeRoute[] = [
  {
    id: 'route-kollam-east',
    name: 'NH-66 North Bypass to Cantonment Elevated Corridor',
    fromArea: 'Low-lying coastal fishing colonies (Zones A & B)',
    toShelterId: 'shelter-kollam-01',
    shelterName: 'St. Aloysius Relief Center',
    status: 'open_verified',
    distanceKm: 2.4,
    estimatedMinutes: 12,
    roadSegments: [
      {
        name: 'Asramam Link Road',
        condition: 'open',
        lastUpdated: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
        source: 'City Traffic Control & Patrol #4',
      },
      {
        name: 'Cantonment Flyover Access',
        condition: 'open',
        lastUpdated: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
        source: 'PWD Roads Division',
      },
    ],
    hazards: ['Mild crosswinds on coastal overpass', 'Avoid low service lanes'],
    lastVerified: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
  },
  {
    id: 'route-alappuzha-canal-bypass',
    name: 'Vazhicherry Canal Embankment to SDV Hall',
    fromArea: 'Kuttanad Inundation Basin Zone 2',
    toShelterId: 'shelter-alappuzha-02',
    shelterName: 'SDV Centennial Community Hall',
    status: 'caution_partial',
    distanceKm: 3.8,
    estimatedMinutes: 25,
    roadSegments: [
      {
        name: 'Canal Bank Road',
        condition: 'waterlogged',
        lastUpdated: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
        source: 'Police Station #2',
      },
      {
        name: 'Collectorate Junction Road',
        condition: 'open',
        lastUpdated: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
        source: 'Traffic Police Patrol',
      },
    ],
    hazards: ['Waterlogging 15-20cm on Canal Bank segment; high-clearance vehicles only'],
    lastVerified: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
];

export const SEED_CONTACTS: EmergencyContact[] = [
  {
    id: 'contact-state-control',
    name: 'State Disaster Emergency Operation Centre (SEOC)',
    phone: '1070',
    agency: 'Kerala SDMA Control Room',
    category: 'disaster_control',
    available24x7: true,
    lastVerified: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    source: 'State Disaster Management Directory',
  },
  {
    id: 'contact-dist-kollam',
    name: 'District Disaster Control Room (Kollam)',
    phone: '1077',
    agency: 'District Collectorate Kollam',
    category: 'disaster_control',
    available24x7: true,
    lastVerified: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    source: 'District Administration',
  },
  {
    id: 'contact-emergency-resp',
    name: 'National Unified Emergency Helpline',
    phone: '112',
    agency: 'Emergency Response Support System (ERSS)',
    category: 'police',
    available24x7: true,
    lastVerified: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    source: 'Ministry of Home Affairs',
  },
  {
    id: 'contact-ndrf-ops',
    name: 'NDRF 4th Battalion Quick Response Unit',
    phone: '+91 44 2684 0000',
    agency: 'National Disaster Response Force',
    category: 'fire_rescue',
    available24x7: true,
    lastVerified: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    source: 'NDRF Regional Headquarters',
  },
];

export const SEED_NOTIFICATION_CHANNELS: NotificationChannelStatus[] = [
  {
    channel: 'in_app',
    name: 'In-App Critical Siren & Visual HUD',
    status: 'active',
    providerName: 'AEGIS Local Realtime Engine (Web Audio + Vibration)',
    details: 'Hardware-synthesized dual-tone siren, screen pulse, offline cache ready.',
    deliveriesCount: 4210,
    failuresCount: 0,
  },
  {
    channel: 'browser_push',
    name: 'Web Push Notifications (W3C Push API)',
    status: 'active',
    providerName: 'Standard Browser Push Service (VAPID)',
    details: 'Dispatched to subscribed desktop and mobile browser service workers.',
    deliveriesCount: 3890,
    failuresCount: 42,
  },
  {
    channel: 'sms',
    name: 'SMS Emergency Broadcast Gateway',
    status: 'demo_sandbox',
    providerName: 'SMS Gateway Adapter (Twilio / CDAC Telecom Sandbox)',
    details: 'DEMO SANDBOX MODE. Real carrier delivery requires telecom aggregator credentials.',
    deliveriesCount: 0,
    failuresCount: 0,
  },
  {
    channel: 'cell_broadcast',
    name: 'Cell Broadcast Emergency Warning (CBC / 3GPP TS 23.041)',
    status: 'not_configured',
    providerName: 'National CBC Gateway Integration Adapter',
    details: 'INTEGRATION READY — Provider gateway not configured. Standard web browsers cannot emit raw RF cell broadcasts directly.',
    deliveriesCount: 0,
    failuresCount: 0,
  },
  {
    channel: 'voice_siren',
    name: 'Automated Voice TTS Broadcast (Web Speech / Gemini)',
    status: 'active',
    providerName: 'AEGIS Speech Engine (Multi-lingual Voice Synthesis)',
    details: 'Spoken text alert playback in English and 7 regional Indian languages.',
    deliveriesCount: 3812,
    failuresCount: 15,
  },
];

export const SEED_EARTHQUAKE_EVENT: EarthquakeEvent = {
  id: 'eq-2026-10-05-01',
  timestamp: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
  source: 'National Center for Seismology (NCS) / USGS Global Seismic Network',
  sourceTier: 2,
  magnitude: 5.4,
  depthKm: 18,
  epicenter: {
    lat: 30.3165,
    lng: 78.0322,
    placeName: 'Chamoli District, Uttarakhand, Western Himalaya',
  },
  classification: 'official_earthquake_information',
  estimatedArrivalSeconds: 0,
  intensityZone: 'strong',
  officialAgencyConfirmed: true,
  safetyRuleNotice:
    'SAFETY COMPLIANCE: AEGIS never claims earthquake prediction. Information shown is detected ground motion and official seismic telemetry from verified seismic networks. In an active tremor: DROP, COVER, HOLD ON.',
};

export const SEED_GROUND_MOTION_SIGNALS: GroundMotionSignal[] = [
  {
    id: 'sig-phone-891',
    deviceId: 'sensor-device-px8-k71',
    timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    peakAccelerationG: 0.14,
    coordinates: { lat: 30.32, lng: 78.05 },
    confidence: 68,
    classification: 'possible_ground_motion_signal',
    notes: 'Single mobile accelerometer tremor detection. Unverified by secondary seismometer grid.',
  },
  {
    id: 'sig-phone-892',
    deviceId: 'sensor-device-s24-m42',
    timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    peakAccelerationG: 0.16,
    coordinates: { lat: 30.33, lng: 78.04 },
    confidence: 72,
    classification: 'possible_ground_motion_signal',
    notes: 'Coincident signal within 1.5km radius. Sensor anomaly check active.',
  },
];

export const INITIAL_CRITICAL_ALERT: EmergencyAlert = {
  id: 'alert-kollam-flood-01',
  eventId: 'evt-kollam-flood-2026',
  version: 2,
  previousVersionId: 'alert-kollam-flood-01-v1',
  disasterType: 'flood',
  severity: 'critical',
  headline: 'FLASH FLOOD EMERGENCY WARNING — IMMEDIATE HIGH-GROUND EVACUATION',
  affectedArea: {
    district: 'Kollam',
    zones: ['Asramam Lowlands', 'Mundakkal Coastal Basin', 'Iravipuram Ward 12'],
    coordinates: { lat: 8.8932, lng: 76.6141, radiusKm: 6.5 },
  },
  whatHappened:
    'Extreme torrential precipitation (182mm in 4 hours) coupled with rising water levels at Kallada river has breached local retention embankments. Low-lying wards face rapid inundation up to 1.5 meters.',
  whatToDo:
    'MOVE TO HIGHER GROUND IMMEDIATELY. Do not attempt to walk, swim, or drive through moving flood waters. Turn off main electrical switches and gas cylinders before leaving.',
  whereToGo:
    'Proceed immediately to St. Aloysius Higher Secondary Relief Center (Beach Road, Cantonment Ward) or nearest designated multi-storey masonry facility.',
  simpleLanguageSummary: {
    whatHappened: 'Severe flooding is occurring right now. Water is rising fast in low areas.',
    whatToDo: 'Leave low areas immediately. Move up to a safe tall building.',
    whereToGo: 'Go to St. Aloysius Relief Center on Beach Road.',
    caveat: 'AI simplification generated for clarity. Follow official emergency guidance.',
  },
  destinationSummary: 'St. Aloysius Relief Center (1.4 km north-east) — Capacity open',
  shelterIds: ['shelter-kollam-01', 'shelter-alappuzha-02'],
  routeIds: ['route-kollam-east'],
  emergencyContactIds: ['contact-state-control', 'contact-dist-kollam', 'contact-emergency-resp'],
  status: 'official_warning',
  source: SEED_SOURCES[0], // SDMA Tier 1
  createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  updatedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
  expiresAt: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
  completeness: {
    score: 92,
    presentFields: [
      'disasterType',
      'severity',
      'affectedArea',
      'whatHappened',
      'whatToDo',
      'whereToGo',
      'shelters',
      'safeRoutes',
      'emergencyContacts',
      'source',
      'expiresAt',
      'accessibilityLanguage',
    ],
    missingFields: ['roadConditions'],
    fieldBreakdown: [
      { field: 'disasterType', label: 'Disaster Type', weight: 12, present: true, valueSummary: 'Flood' },
      { field: 'severity', label: 'Alert Severity Level', weight: 10, present: true, valueSummary: 'CRITICAL' },
      { field: 'affectedArea', label: 'Affected Geographic Zone', weight: 14, present: true, valueSummary: 'Kollam [3 zones]' },
      { field: 'whatHappened', label: 'Incident Description', weight: 12, present: true, valueSummary: 'Embankment breach 1.5m' },
      { field: 'whatToDo', label: 'Prescribed Protective Action', weight: 14, present: true, valueSummary: 'Move to higher ground immediately' },
      { field: 'whereToGo', label: 'Evacuation Destination', weight: 10, present: true, valueSummary: 'St. Aloysius Relief Center' },
      { field: 'shelters', label: 'Verified Shelter Facility', weight: 8, present: true, valueSummary: '2 shelters linked' },
      { field: 'safeRoutes', label: 'Safe Evacuation Route', weight: 6, present: true, valueSummary: '1 verified open route' },
      { field: 'roadConditions', label: 'Road Transit Conditions', weight: 4, present: false, valueSummary: 'Not provided by source' },
      { field: 'emergencyContacts', label: 'Helpline / Emergency Contact', weight: 6, present: true, valueSummary: '3 hotlines attached' },
      { field: 'source', label: 'Authorized Source & Provenance', weight: 8, present: true, valueSummary: 'SDMA Tier 1' },
      { field: 'expiresAt', label: 'Warning Expiration Window', weight: 4, present: true, valueSummary: 'Valid for next 4 hours' },
      { field: 'accessibilityLanguage', label: 'Multilingual Ready', weight: 2, present: true, valueSummary: '8 Indian languages ready' },
    ],
  },
  gaps: [
    {
      id: 'gap-road-kollam-01',
      field: 'roadConditions',
      label: 'Secondary Road Submergence Status Unknown',
      severity: 'warning',
      status: 'under_review',
      evidence: 'Source warning does not detail local ward-level cross streets; only main bypass is officially surveyed.',
      explanation: 'Unverified waterlogging may exist on unpaved coastal lanes.',
      suggestedAction: 'Motorists must remain on elevated primary arteries only.',
    },
  ],
  conflicts: [
    {
      id: 'conf-kollam-evac-time',
      field: 'expiresAt',
      fieldLabel: 'Evacuation Deadline / River Crest Window',
      sourceA: {
        sourceId: 'src-ksdma-gov',
        sourceName: 'SDMA Disaster Operations Cell (Tier 1)',
        tier: 1,
        value: 'Immediate mandatory evacuation until 8:00 PM',
        timestamp: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
      },
      sourceB: {
        sourceId: 'src-redcross-ops',
        sourceName: 'Red Cross Field Volunteer Advisory (Tier 3)',
        tier: 3,
        value: 'Relocation recommended by 6:00 PM before daylight loss',
        timestamp: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
      },
      status: 'authority_adjudicated',
      explanation:
        'Discrepancy in recommended deadline. SDMA Tier 1 authority takes legal precedence; early movement prior to darkness (6:00 PM) strongly urged by operational teams.',
      adjudicatedValue: 'Mandatory completion by 6:00 PM (Prioritizing earlier safety window per Tier 1 endorsement).',
    },
  ],
  freshness: {
    lastUpdated: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    receivedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    ageMinutes: 4,
    status: 'fresh',
    thresholdMinutes: 45,
  },
  provenance: {
    sourceId: 'src-ksdma-gov',
    sourceName: 'State Disaster Management Authority (SDMA)',
    sourceTier: 1,
    receivedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    dataType: 'OFFICIAL_EMERGENCY_ORDER',
    verifiedBy: 'Dr. K. Narayanan, IAS (Emergency Relief Commissioner)',
    verifierRole: 'State Incident Commander',
    auditId: 'AEGIS-AUDIT-KL-20261005-9921',
    inputRawTextPreview:
      'SDMA/DIS/ORD/2026/88: Flash flood alert for coastal Kollam wards. Breaches detected along Kallada basin. Mandatory evacuation to higher ground.',
    modificationHistory: [
      {
        timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        modifier: 'Duty Officer Nair',
        fieldChanged: 'affectedArea.zones',
        previousValue: 'Asramam Lowlands only',
        newValue: 'Asramam Lowlands + Mundakkal Coastal Basin + Iravipuram Ward 12',
      },
    ],
  },
  assuranceScorecard: {
    overallScore: 92,
    completeness: 92,
    freshness: 98,
    sourceQuality: 100,
    conflictScore: 85,
    accessibilityScore: 95,
    verificationScore: 100,
    formulaExplanation:
      'Overall 92%: High completeness (92%), Official Tier 1 Source (100%), Fresh within 4 mins (98%), Single resolved conflict (85%), Multi-lingual verified (95%).',
  },
  translations: {
    ml: {
      headline: 'മിന്നൽ പ്രളയ മുന്നറിയിപ്പ് — ഉടനടി സുരക്ഷിത സ്ഥാനങ്ങളിലേക്ക് മാറുക',
      whatHappened:
        'കനത്ത മഴയെത്തുടർന്ന് കല്ലടയാറ്റിലെ ജലനിരപ്പ് ഉയർന്നതിനാൽ താഴ്ന്ന പ്രദേശങ്ങളിൽ വെള്ളപ്പൊക്ക സാധ്യതയുണ്ട്. 1.5 മീറ്റർ വരെ വെള്ളം ഉയർന്നേക്കാം.',
      whatToDo:
        'ഉടനടി ഉയർന്ന പ്രദേശങ്ങളിലേക്ക് മാറുക. ഒഴുകുന്ന വെള്ളത്തിലൂടെ നടക്കാനോ വാഹനമോടിക്കാനോ ശ്രമിക്കരുത്. വൈദ്യുതി, ഗ്യാസ് സ്വിച്ചുകൾ ഓഫ് ചെയ്യുക.',
      whereToGo: 'ബീച്ച് റോഡിലുള്ള സെന്റ് അലോഷ്യസ് ഹയർ സെക്കൻഡറി ദുരിതാശ്വാസ ക്യാമ്പിലേക്ക് ഉടൻ മാറുക.',
      isVerified: true,
    },
    hi: {
      headline: 'आकस्मिक बाढ़ आपातकालीन चेतावनी — तत्काल सुरक्षित स्थान पर जाएं',
      whatHappened:
        'अत्यधिक भारी बारिश के कारण जलस्तर खतरे के निशान से ऊपर पहुंच गया है। निचले इलाकों में 1.5 मीटर तक पानी भरने का खतरा है।',
      whatToDo:
        'तुरंत ऊंचे स्थानों पर जाएं। बहते पानी में चलने या गाड़ी चलाने का प्रयास न करें। बिजली और गैस बंद कर दें।',
      whereToGo: 'बीच रोड स्थित सेंट अलॉयसियस रिलीफ कैंप या निकटतम पक्की बहुमंजिला इमारत में जाएं।',
      isVerified: true,
    },
    ta: {
      headline: 'திடீர் வெள்ள அவசர எச்சரிக்கை — உடனடியாக பாதுகாப்பான இடத்திற்கு செல்லவும்',
      whatHappened:
        'கடும் மழையால் ஆற்றில் நீர்மட்டம் உயர்ந்துள்ளது. தாழ்வான பகுதிகளில் 1.5 மீட்டர் வரை வெள்ளம் சூழக்கூடும்.',
      whatToDo:
        'உடனடியாக மேடான பகுதிக்கு செல்லவும். ஓடும் வெள்ளத்தில் நடக்கவோ வாகனம் ஓட்டவோ வேண்டாம்.',
      whereToGo: 'பீச் ரோட்டில் உள்ள செயின்ட் அலோசியஸ் நிவாரண முகாமுக்கு செல்லவும்.',
      isVerified: true,
    },
    te: {
      headline: 'ఆకస్మిక వరద అత్యవసర హెచ్చరిక — వెంటనే సురక్షిత ప్రాంతాలకు వెళ్లండి',
      whatHappened: 'భారీ వర్షాల కారణంగా నది ఉధృతంగా ప్రవహిస్తోంది. లోతట్టు ప్రాంతాలలో నీరు వేగంగా చేరుతోంది.',
      whatToDo: 'వెంటనే ఎత్తైన ప్రాంతాలకు తరలివెళ్లండి. ప్రవహించే నీటిలో వాహనాలు నడపవద్దు.',
      whereToGo: 'బీచ్ రోడ్డులోని సెయింట్ అలోసియస్ సహాయక శిబిరానికి వెళ్లండి.',
      isVerified: true,
    },
    kn: {
      headline: 'ಧಿಡೀರ್ ಪ್ರವಾಹ ತುರ್ತು ಎಚ್ಚರಿಕೆ — ತಕ್ಷಣ ಸುರಕ್ಷಿತ ಸ್ಥಳಕ್ಕೆ ತೆರಳಿ',
      whatHappened: 'ಭಾರೀ ಮಳೆಯಿಂದಾಗಿ ನದಿ ನೀರಿನ ಮಟ್ಟ ಹೆಚ್ಚಿದ್ದು ತಗ್ಗು ಪ್ರದೇಶಗಳಲ್ಲಿ ಪ್ರವಾಹದ ಭೀತಿ ಇದೆ.',
      whatToDo: 'ಕೂಡಲೇ ಎತ್ತರದ ಪ್ರದೇಶಗಳಿಗೆ ತೆರಳಿ. ಹರಿಯುವ ನೀರಿನಲ್ಲಿ ವಾಹನ ಚಲಾಯಿಸಬೇಡಿ.',
      whereToGo: 'ಬೀಚ್ ರಸ್ತೆಯ ಸೇಂಟ್ ಅಲೋಶಿಯಸ್ ಪರಿಹಾರ ಕೇಂದ್ರಕ್ಕೆ ತೆರಳಿ.',
      isVerified: true,
    },
    mr: {
      headline: 'अचानक महापुराचा इशारा — त्वरित सुरक्षित स्थळी स्थलांतर करा',
      whatHappened: 'मुसळधार पावसामुळे नदीची पाणीपातळी वाढली असून सखल भागात पुराचा धोका निर्माण झाला आहे.',
      whatToDo: 'तातडीने उंच जागेवर जा. वाहत्या पाण्यातून जाण्याचा प्रयत्न करू नका.',
      whereToGo: 'बीच रोडवरील सेंट अलॉयसियस मदत केंद्रात जा.',
      isVerified: true,
    },
    bn: {
      headline: 'হড়পা বান জরুরি সতর্কতা — অবিলম্বে উঁচু স্থানে আশ্রয় নিন',
      whatHappened: 'ভারী বৃষ্টির কারণে নদীর জলস্তর বিপদসীমার উপর দিয়ে প্রবাহিত হচ্ছে। নিম্নাঞ্চল প্লাবিত হওয়ার আশঙ্কা।',
      whatToDo: 'অবিলম্বে নিরাপদ উঁচু স্থানে চলে যান। খরস্রোতা জলে হাঁটার বা গাড়ি চালানোর চেষ্টা করবেন না।',
      whereToGo: 'বীচ রোডের সেন্ট অ্যালোয়সিয়াস ত্রাণ শিবিরে অবিলম্বে আশ্রয় নিন।',
      isVerified: true,
    },
  },
  deliveryStats: {
    inAppDelivered: 4210,
    pushDelivered: 3890,
    smsDelivered: 0,
    cellBroadcastStatus: 'integration_ready_unconfigured',
    voiceCallsAttempted: 3812,
    acknowledgementCount: 1845,
    totalTargetPopEstimate: 14500,
  },
  auditTrailId: 'AUDIT-AEGIS-KL-20261005-001',
};

export const SEED_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'log-001',
    timestamp: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    actorEmail: 'system-ingest@aegis.gov',
    actorRole: 'authority',
    action: 'EVENT_INGESTED',
    entityId: 'evt-kollam-flood-2026',
    summary: 'Raw meteorological and river gauge alerts received from IMD & CWC sensors.',
    auditHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  },
  {
    id: 'log-002',
    timestamp: new Date(Date.now() - 36 * 60 * 1000).toISOString(),
    actorEmail: 'ai-engine@aegis.gov',
    actorRole: 'authority',
    action: 'AI_EXTRACTION_COMPLETED',
    entityId: 'alert-kollam-flood-01-v1',
    summary: 'Extracted structured disaster parameters. Completeness scored at 68% (Missing shelter, road condition).',
    auditHash: 'a5893b1d798689531e247492c730fc977e231bcde41b7149a4a7541b65b6eb06',
  },
  {
    id: 'log-003',
    timestamp: new Date(Date.now() - 34 * 60 * 1000).toISOString(),
    actorEmail: 'ai-engine@aegis.gov',
    actorRole: 'authority',
    action: 'CONFLICT_DETECTED',
    entityId: 'alert-kollam-flood-01-v1',
    summary: 'Detected evacuation window discrepancy between SDMA (8:00 PM) and Red Cross (6:00 PM).',
    auditHash: '6d0e6592239d5e6833b5a1b327b7c2a713b72c47bc863a0a3ecad07856ab25bc',
  },
  {
    id: 'log-004',
    timestamp: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    actorEmail: 'officer.nair@aegis.gov',
    actorRole: 'authority',
    action: 'ALERT_APPROVED',
    entityId: 'alert-kollam-flood-01-v2',
    summary: 'Authority verified St. Aloysius shelter allocation and approved mandatory evacuation order.',
    auditHash: '7a8f152d2f34589d38c11e3b615c89304128a594892c9b46f5342617f1a8c9e0',
  },
  {
    id: 'log-005',
    timestamp: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    actorEmail: 'officer.nair@aegis.gov',
    actorRole: 'authority',
    action: 'ALERT_PUBLISHED',
    entityId: 'alert-kollam-flood-01',
    summary: 'Official critical alert broadcasted across In-App, Web Push, and Voice channels.',
    auditHash: '9f83a42d87a2c689b12480392019a3b681729048a129481bc92847a98129e0ab',
  },
];
